<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="pwcl-QUwOcBzlWD" failures="2" tests="9" name="RetryMultipleFailTestcases" time="0.074" errors="0" timestamp="2022-06-19T14:03:57 IST">
  <testcase classname="ReTryAnalyser.MyTest1" name="Test1" time="0.011">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="ReTryAnalyser.MyTest1" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="ReTryAnalyser.MyTest1" name="Test1" time="0.007">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="ReTryAnalyser.MyTest1" name="Test1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ReTryAnalyser.MyTest1.Test1(MyTest1.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="ReTryAnalyser.MyTest1" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="ReTryAnalyser.MyTest1" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="ReTryAnalyser.MyTest1" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="ReTryAnalyser.MyTest1" name="Test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at ReTryAnalyser.MyTest1.Test2(MyTest1.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="ReTryAnalyser.MyTest1" name="Test3" time="0.001"/>
</testsuite> <!-- RetryMultipleFailTestcases -->
